version: '2'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        volumes:
            - './docker/db/postgres_data:/var/lib/postgresql/data'
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin'
            POSTGRES_DB: 'testdb'
        ports:
            - '5432:5432'

    src:
        build: .
        working_dir: /app
        ports: 
            - '8080:8080'
        depends_on:
            - postgres
